name: Dump
 #
on:
  push:
    paths-ignore:
      - '*.md'
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkouts
         uses: actions/checkout@v2

       - name: Clone Dumpyara
         run: |
              git clone https://github.com/ksauraj1/dumpyara.git
              
       - name: Setup Dumpyara environment
         working-directory: dumpyara
         run: |
              sudo bash setup.sh
              git config --global user.name "ksauraj1"
              git config --global user.email "kumarsauraj24@gmail.com"

       - name: Setup config envs
         working-directory: dumpyara
         run: |
              echo "${{ secrets.GIT_TOKEN }}" > .githubtoken
              echo "${{ secrets.GIT_ORG_NAME }}" > .github_orgname
              echo "${{ secrets.BOT_TOKEN }}" > .tgtoken
              echo "${{ secrets.CHAT_ID }}" > .tgchannel  #or chat group example: @box_dumps
# make sure to change git credentials as in https://github.com/mirrordump/dumpyara/commit/19016994794424b5d88c2e28add1924567b28c38
       - name: Running Dumpyara
         working-directory: dumpyara
         run: |
              ./dumpyara.sh "$ROM_URL"
#
env:
  ROM_URL: https://download.wetransfer.com/usgv/2c488a6e4df983b668d9c40951023cec20210627140352/df9edf417d9182951ae5f9c805e5fe2bb7e5fd83/PixelExperience_RMX2020-11.0-20210627-1239-UNOFFICIAL.zip?token=eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MjQ4MDUzMTIsImV4cCI6MTYyNDgwNTkxMiwidW5pcXVlIjoiMmM0ODhhNmU0ZGY5ODNiNjY4ZDljNDA5NTEwMjNjZWMyMDIxMDYyNzE0MDM1MiIsImZpbGVuYW1lIjoiUGl4ZWxFeHBlcmllbmNlX1JNWDIwMjAtMTEuMC0yMDIxMDYyNy0xMjM5LVVOT0ZGSUNJQUwuemlwIiwid2F5YmlsbF91cmwiOiJodHRwOi8vc3Rvcm0taW50ZXJuYWwuc2VydmljZS51cy1lYXN0LTEud2V0cmFuc2Zlci5uZXQvYXBpL3dheWJpbGxzP3NpZ25lZF93YXliaWxsX2lkPWV5SmZjbUZwYkhNaU9uc2liV1Z6YzJGblpTSTZJa0pCYUhCQ1FsZFRNM2RWUFNJc0ltVjRjQ0k2SWpJd01qRXRNRFl0TWpkVU1UUTZOVGc2TXpJdU1EQXdXaUlzSW5CMWNpSTZJbmRoZVdKcGJHeGZhV1FpZlgwLS04MTYwODM0N2RhMDM2NjA1ZjU0OTY0MTJlMTZlNTVmOTA1NGJmMmE5MGEzZGIyYjI1ZDNhMDU4YmI3ODg3NzAwIiwiZmluZ2VycHJpbnQiOiJkZjllZGY0MTdkOTE4Mjk1MWFlNWY5YzgwNWU1ZmUyYmI3ZTVmZDgzIiwiY2FsbGJhY2siOiJ7XCJmb3JtZGF0YVwiOntcImFjdGlvblwiOlwiaHR0cDovL3Byb2R1Y3Rpb24uZnJvbnRlbmQuc2VydmljZS5ldS13ZXN0LTEud3Q6MzAwMC93ZWJob29rcy9iYWNrZW5kXCJ9LFwiZm9ybVwiOntcInRyYW5zZmVyX2lkXCI6XCIyYzQ4OGE2ZTRkZjk4M2I2NjhkOWM0MDk1MTAyM2NlYzIwMjEwNjI3MTQwMzUyXCIsXCJkb3dubG9hZF9pZFwiOjEyNDU2NTc4MjQxfX0ifQ.AlQ6t13MYExdIKtIACw6PbU-myPa3R0CY71MBZK89wM
